### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by koolkunz** [deCodeIt/book-my-show-notification#2]
ERROR: Complete output from command python setup.py egg_info:
    ERROR: running egg_info
    c:\users\kunal goel\appdata\local\programs\python\python37-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    error: PyObjC requires macOS to build
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Kunal Goel\AppData\Local\Temp\pip-install-b0s8ylxe\pyobjc-core\

Any alternatives to make this work on windows or is VM Mac Os the way to go?

**Comment by koolkunz** [comment]
Guess not.. I installed MacOs on VM and its working so thanks

**Comment by deCodeIt** [comment]
While developing the script, the platform decided was macOS. While the code should work on Linux, macOS as well as Windows there are still dependency issues.
I'm working on to fix them as soon as possible.
