### ISSUE TITLE
Can I use it in windows?

### ISSUE THREAD

**Issue by KRISHNA-git11** [deCodeIt/book-my-show-notification#5]

**Comment by KRISHNA-git11** [comment]
It says PyObjC requires macOS to build

**Comment by deCodeIt** [comment]
I haven't tested it out on windows. Have run this on mac. PyObjC is used by the `playsound` library to play sound. If you don't want the alert you can perhaps remove that library and modify `def soundAlarm(...)` method with whatever cmd that works on windows.
